### ISSUE TITLE
Error (should we have some sort of babel setup?)

### ISSUE THREAD

**Issue by tslater** [IceEnd/electron-watch#1]
```
Uncaught Exception:
Error: Cannot find module 'babel-register'
    at Module._resolveFilename (internal/modules/cjs/loader.js:584:15)
    at Function.Module._resolveFilename (/Users/tyler/jolt/code/blackjack/node_modules/electron/dist/Electron.app/Contents/Resources/electron.asar/common/reset-search-paths.js:43:12)
    at Function.Module._load (internal/modules/cjs/loader.js:510:25)
    at Module.require (internal/modules/cjs/loader.js:640:17)
    at Function.Module._preloadModules (internal/modules/cjs/loader.js:809:12)
    at Object.<anonymous> (/Users/tyler/jolt/code/blackjack/node_modules/electron/dist/Electron.app/Contents/Resources/default_app.asar/main.js:74:10)
    at Object.<anonymous> (/Users/tyler/jolt/code/blackjack/node_modules/electron/dist/Electron.app/Contents/Resources/default_app.asar/main.js:204:3)
    at Module._compile (internal/modules/cjs/loader.js:693:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:704:10)
    at Module.load (internal/modules/cjs/loader.js:602:32)
```

**Comment by IceEnd** [comment]
No need.
Your main process script needs babel to compile?
